const items = [
    {
        "id": "apple-watch-1",
        "name": "Apple Watch",
        "color": "grey",
        "price": "64999",
        "orderable-qty": "50",
        "ram": "6 GB",
        "storage": "512 GB",
        "sku": [],
        "promotions":[],
        "size":"6.1 Inch",
        "camera": "12 MP",
        "warrenty": "1 year",
        "processor": "B 13 Bionic Chip",
        "emi": [],
        "reviews": [],
        "discount": [],
        "addon": [],
        "pics": [],
        "offers": [],
        "version": ""
    },
    {
        "id": "apple-watch-2",
        "name": "Apple Watch",
        "color": "grey",
        "price": "64999",
        "orderable-qty": "50",
        "ram": "6 GB",
        "storage": "512 GB",
        "sku": [],
        "promotions":[],
        "size":"6.1 Inch",
        "camera": "12 MP",
        "warrenty": "1 year",
        "processor": "B 13 Bionic Chip",
        "emi": [],
        "reviews": [],
        "discount": [],
        "addon": [],
        "pics": [],
        "offers": [],
        "version": ""
    },
    {
        "id": "apple-watch-3",
        "name": "Apple Watch",
        "color": "grey",
        "price": "64999",
        "orderable-qty": "50",
        "ram": "6 GB",
        "storage": "512 GB",
        "sku": [],
        "promotions":[],
        "size":"6.1 Inch",
        "camera": "12 MP",
        "warrenty": "1 year",
        "processor": "B 13 Bionic Chip",
        "emi": [],
        "reviews": [],
        "discount": [],
        "addon": [],
        "pics": [],
        "offers": [],
        "version": ""
    },
    {
        "id": "apple-watch-4",
        "name": "Apple Watch",
        "color": "grey",
        "price": "64999",
        "orderable-qty": "50",
        "ram": "6 GB",
        "storage": "512 GB",
        "sku": [],
        "promotions":[],
        "size":"6.1 Inch",
        "camera": "12 MP",
        "warrenty": "1 year",
        "processor": "B 13 Bionic Chip",
        "emi": [],
        "reviews": [],
        "discount": [],
        "addon": [],
        "pics": [],
        "offers": [],
        "version": ""
    }
]